# Generated by Django 2.0.4 on 2018-05-27 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(default=datetime.datetime(2018, 5, 27, 1, 31, 4, 995939, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
